version: '3'
services:
  spillman-api-prod:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: sccity/spillman-api:prod
    container_name: spillman-api-prod
    environment:
      - TZ=America/Denver
    ports:
      - "8888:5000"
    volumes:
      - "/etc/sccity/spillman-api-prod.yaml:/app/config/settings.yaml:ro"
    restart: unless-stopped
    user: "1435:1435" 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  spillman-api-dev:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: sccity/spillman-api:dev
    container_name: spillman-api-dev
    environment:
      - TZ=America/Denver
    ports:
      - "8889:5000"
    volumes:
      - "/etc/sccity/spillman-api-dev.yaml:/app/config/settings.yaml:ro"
    restart: unless-stopped
    user: "1435:1435" 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  spillman-api-proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: sccity/spillman-api:proxy
    container_name: spillman-api-proxy
    environment:
      - TZ=America/Denver
    ports:
      - "80:80"
    volumes:
      - "/etc/sccity/spillman-api-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/sccity/spillman-api-proxy-dev.conf:/etc/nginx/conf.d/spillman-api-proxy-dev.conf:ro"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M